context:
  version: "0.5.0"

package:
  name: sleek
  version: ${{ version }}

source:
  url: https://github.com/nrempel/sleek/archive/v${{ version }}.tar.gz
  sha256: fcb589fdc5ece8c050883ff0b56aec6bd25e2e4d6e77a1d52e870535d66fdf67

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sleek --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Sleek is a CLI tool for formatting SQL.
  homepage: https://github.com/nrempel/sleek
  repository: https://github.com/nrempel/sleek

extra:
  recipe-maintainers:
    - danielnachun
