context:
  version: "0.4.0"

package:
  name: sleek
  version: ${{ version }}

source:
  url: https://github.com/nrempel/sleek/archive/v${{ version }}.tar.gz
  sha256: d4ebd91cfa8478cc5da1e3b5a4ebe0acc4a854970e1fc3638f6dd15b21eccf7b

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - sleek --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Sleek is a CLI tool for formatting SQL.
  homepage: https://github.com/nrempel/sleek
  repository: https://github.com/nrempel/sleek

extra:
  recipe-maintainers:
    - danielnachun
